name: Build website
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: build
      uses: docker://silex/emacs
      with:
        args: ./build-site.sh
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      if: success()
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./docs
