name: Build website
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: silex/emacs
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: build
      uses: silex/emacs
      with:
        args: ./build-site.sh
