name: Build website
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: build
      uses: docker://silex/emacs
      with:
        args: ./build-site.sh
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      if: success()
      with:
        branch: gh-pages
        folder: ./docs
